---
apiVersion: v1
kind: Service
metadata:
  name: teacher-training-entitlement-maintenance
spec:
  selector:
    app: teacher-training-entitlement-maintenance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
