apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: development.teacher-training-entitlement.education.gov.uk
spec:
  ingressClassName: nginx
  rules:
  - host: development.teacher-training-entitlement.education.gov.uk
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: teacher-training-entitlement-development
            port:
              number: 80
