apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teacher-training-entitlement-temp.test.teacherservices.cloud
spec:
  ingressClassName: nginx
  rules:
  - host: teacher-training-entitlement-temp.test.teacherservices.cloud
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: teacher-training-entitlement-development
            port:
              number: 80
