---
check_if_your_workplace_is_registered_with_ofsted:
  url: "https://reports.ofsted.gov.uk/childcare"
feedback_form:
   url: "https://forms.office.com/pages/responsepage.aspx?id=yXfS-grGoU2187O4s0qC-XFs6Aph9JFAlL3W5RWOR_5URTJBQUEwWDBYWFRGRE5BMk8zUFhGT0tSMy4u&route=shorturl"
find_out_about_npq_courses:
   url: "https://www.gov.uk/guidance/national-professional-qualification-npq-courses"
find_a_lost_trn:
  url: "https://find-a-lost-trn.education.gov.uk/start"
funding_for_npqs:
  url: "https://www.gov.uk/guidance/funding-for-national-professional-qualifications-npqs"
get_a_trn:
  url: "https://authorise-access-to-a-teaching-record.education.gov.uk/request-trn?AccessToken=SqjgaHbrdofsSL5z"
  skip_check: true
gias_establishment_search:
  url: "https://get-information-schools.service.gov.uk/Search?SelectedTab=Establishments"
join_the_maths_teaching_for_mastery_programme:
  url: "https://www.gov.uk/guidance/join-the-maths-teaching-for-mastery-programme"
learn_about_npqs:
  url: "https://www.gov.uk/government/publications/national-professional-qualifications-npqs"
learn_about_trns:
  url: "https://www.gov.uk/guidance/teacher-reference-number-trn"
teaching_identity_cookies:
  url: "https://teaching-identity.education.gov.uk/cookies"
